- name: Create VM network
  hosts: all
  gather_facts: false

  tasks:
    - name: Create service
      redhat.openshift.k8s:
        state: present
        namespace: "{{ target_ns }}"
        inline:
          apiVersion: v1
          kind: Service
          metadata:
            name: front-service
          spec:
            ports:
              - port: 80
                targetPort: 80
            selector:
              vm.kubevirt.io/name: "{{ (vm | from_yaml)[0].name }}"

    - name: Create route
      redhat.openshift.k8s:
        state: present
        namespace: "{{ target_ns }}"
        inline:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            name: front-route
          spec:
            host: "front-famous-quotes.apps.ocp4.example.com"
            port:
              targetPort: 80
            to:
              kind: Service
              name: front-service
