---
- name: MySQL VM installation and configuration
  hosts: "{{ target_ns }}-{{ (vm | from_yaml)[1].name }}"
  gather_facts: true
  become: true
  tasks:

  - name: Install MySQL packages
    ansible.builtin.dnf:
      state: present
      name:
        - mariadb-server
        - firewalld

  - name: Ensure firewalld is running
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: yes

  - name: Open Firewall for MySQL use
    ansible.builtin.firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
    - mysql

  - name: Ensure MySQL is running at boot
    ansible.builtin.service:
      name: mariadb
      enabled: yes
      state: started

  - name: Set up SQL commands
    ansible.builtin.template:
      src: "{{ playbook_dir }}/../files/prime.sql"
      dest: /tmp/prime.sql
      mode: 400
    when: mysql_root_password is defined

  - name: Set up root account
    ansible.builtin.shell: mysql </tmp/prime.sql
    when: mysql_root_password is defined

  - name: Set up database
    ansible.builtin.template:
      src: "{{ playbook_dir }}/../files/database.sql"
      dest: /tmp/database.sql
      mode: 400
    when: mysql_root_password is defined

  - name: Import database
    ansible.builtin.shell: mysql -ucloud-user -p"{{ mysql_root_password }}" </tmp/database.sql
    when: mysql_root_password is defined
